// ==========================================
// DOM MANIPULATION PRACTICE CODE
// ==========================================

// --- Part 02: The Global Objects ---
console.log("--- Global Objects ---");
console.log(window);        // The global window object
console.log(document);      // The DOM document object
console.log(document === window.document); // true


// --- Part 03: Selecting Elements from the DOM ---
console.log("\n--- Selecting Elements ---");

// getElementById
const h1Single = document.getElementById("h1");
console.log("getElementById:", h1Single);

const notFound = document.getElementById("nonexistent");
console.log("Not found:", notFound); // null

// querySelector
const h1Query = document.querySelector("h1");
const headingClass = document.querySelector(".heading");
const inputElement = document.querySelector('input[type="text"]');
const childNode = document.querySelector("div > p");

// querySelectorAll
const allHeadings = document.querySelectorAll("#h1");
console.log("querySelectorAll NodeList:", allHeadings);
console.log("Length of NodeList:", allHeadings.length);

// Iterating through NodeList
allHeadings.forEach((heading, index) => {
    console.log(`Heading ${index + 1}: ${heading.textContent}`);
});

// Convert NodeList to Array
const headingArray = Array.from(allHeadings);
console.log("Is it an array now?", Array.isArray(headingArray));


// --- Part 04: Reading and Modifying Content ---
console.log("\n--- Modifying Content ---");
const contentDemo = document.querySelector("#content-demo");
const hiddenDemo = document.querySelector("#hidden-demo");

// textContent vs innerHTML vs innerText
console.log("textContent:", contentDemo.textContent); // "Hello World"
console.log("innerHTML:", contentDemo.innerHTML);     // "Hello <b>World</b>"
console.log("innerText (ignores hidden):", hiddenDemo.innerText); // "Hello World"
console.log("textContent (shows hidden):", hiddenDemo.textContent); // "Hello Hidden World"

// Writing content
contentDemo.innerHTML = "<b>Bold</b> text generated by JS";


// --- Part 05: Working with Attributes ---
console.log("\n--- Attributes ---");
const attrDemo = document.querySelector("#attr-demo");
const btn = document.querySelector("#btn");

// setAttribute
attrDemo.setAttribute("style", "background-color: pink; font-size: 20px; padding: 10px;");
btn.setAttribute("disabled", "true");
attrDemo.setAttribute("data-custom", "myValue");

// getAttribute
console.log("Get style attribute:", attrDemo.getAttribute("style"));
console.log("Get non-existent:", attrDemo.getAttribute("nonexistent")); // null

// Checking and Removing
console.log("Has disabled?", btn.hasAttribute("disabled")); // true
btn.removeAttribute("disabled"); // Button enabled again
console.log("All attributes of btn:", btn.attributes);


// --- Part 06: Working with Classes ---
console.log("\n--- Classes ---");
const classDemo = document.querySelector("#class-style-demo");

classDemo.classList.add("random");
classDemo.classList.add("highlight", "large-text");
classDemo.classList.remove("random");
classDemo.classList.toggle("primary-bg"); // Adds it since it doesn't exist

console.log("All classes on element:", classDemo.classList);


// --- Part 07: Working with Styles ---
console.log("\n--- Styles ---");
// Dynamic one-off styles directly via JS
classDemo.style.border = "2px solid black";
classDemo.style.borderRadius = "10px";
classDemo.style.marginTop = "30px";
console.log("Inline background color (from class? NO):", classDemo.style.backgroundColor); // Empty, because it's set via class


// --- Part 08: Dataset and Custom Attributes ---
console.log("\n--- Dataset ---");
const buyBtn = document.querySelector("#buy-btn");

// Setting via dataset
buyBtn.dataset.hello = "hii";
buyBtn.dataset.helloDosto = "hii"; 
buyBtn.dataset.userId = "12345";

// Reading from HTML dataset attributes
buyBtn.addEventListener("click", function() {
    const productId = this.dataset.productId;
    const price = this.dataset.price;
    console.log(`Adding product ${productId} to cart, price: $${price}`);
});


// --- Part 09: Creating and Adding Elements ---
console.log("\n--- Creating & Adding Elements ---");
const body = document.querySelector("body");

// createElement
const newDiv = document.createElement("div");
newDiv.textContent = "I am a newly created DIV!";
newDiv.style.backgroundColor = "lightgreen";
newDiv.style.padding = "10px";
newDiv.style.marginTop = "10px";

// appendChild
body.appendChild(newDiv);

// append & prepend
const p1 = document.createElement("p");
p1.textContent = "Appended text.";
const p2 = document.createElement("p");
p2.textContent = "Prepended text! I am first now.";

body.append(p1, " Just some random raw string appended.");
body.prepend(p2);

// insertBefore
const productList = document.querySelector("#product-list");
const newItem = document.createElement("li");
newItem.textContent = "Inserted Item (Before 3rd child)";
const referenceNode = productList.children[2]; // Product C

productList.insertBefore(newItem, referenceNode);


// --- Part 10: Removing and Cloning Elements ---
console.log("\n--- Removing & Cloning ---");

// remove()
const removeMe = document.querySelector("#h1-remove");
removeMe.remove();

// cloneNode()
const original = document.querySelector("#product-list-one");
const deepClone = original.cloneNode(true);   // Deep clone (with children)
const shallowClone = original.cloneNode(false); // Shallow clone (no children)

deepClone.classList.add("clone");
body.append(deepClone);


// --- Part 11: Working with Children ---
console.log("\n--- Children vs ChildNodes ---");
const parentElement = document.querySelector("#parent");

console.log("children (HTMLCollection - elements only):", parentElement.children);
console.log("childNodes (NodeList - includes text nodes/spaces):", parentElement.childNodes);

// Accessing by index
console.log("First element child:", parentElement.children[0]);
console.log("Last element child:", parentElement.children[parentElement.children.length - 1]);